#!/usr/bin/env node
const { checkCommit, checkEmail, checkFileCase, checkFileExplanatory } = require('./check.js');
const testEmail = /100\.com$/ || /@qq\.com$/;
const path = require('path');

const _path = path.resolve() + '/src';

const commitCheck = async () => {
    await checkFileCase(_path);
    await checkCommit();
    await checkEmail(testEmail);
    await checkFileExplanatory(_path);
};

commitCheck();
