#!/usr/bin/env node
const chalk = require('chalk')
const fs = require('fs');
const childProcess = require('child_process')

const email = childProcess.execSync('git config user.email').toString().trim();
const msg = fs.readFileSync(process.argv[2], 'utf-8').trim(); // 索引 2 对应的 commit 消息文件
const commitRE = /^(feat|fix|docs|style|refactor|perf|test|workflow|build|ci|chore|release|workflow)(\(.+\))?: .{1,100}/;

if (!commitRE.test(msg)) {
  console.log(chalk.yellow(
    '  不合法的 commit 消息格式，请使用正确的提交格式：\n' +
    '  fix: handle events on blur (close #28)：\n' +
    '  详情请查看 git commit 提交规范：https://github.com/woai3c/Front-end-articles/blob/master/git%20commit%20style.md'
  ))
  process.exit(1);
}
const testEmail = /100\.com$/ || /@qq\.com$/
if (!testEmail.test(email)) {
  console.log(chalk.red('此用户没有权限，具有权限的用户为： xxx@qq.com或者100.com'))
  process.exit(1);
}