#!/bin/bash
# /bin/sh 相当于 /bin/bash --posix
# sh跟bash的区别，实际上就是bash有没有开启posix模式的区别。so，可以预想的是，
# 如果第一行写成 #!/bin/bash --posix，那么脚本执行效果跟#!/bin/sh是一样的（遵循posix的特定规范，有可能就包括这样的规范：“当某行代码出错时，不继续往下解释”）



# 执行 lint 脚本，如果不正确需要将退出码设为非零
npm run lint

# 获取上面脚本的退出码
exitCode="$?"
exit $exitCode